### PR TITLE
chore: move CNAME into docs and copy on build

### PR DESCRIPTION
**Pull request by AndersDJohnson**
The `.js.org` site needs the `CNAME` file in the docs site root, so copying into the docs build directory on docs publish. I've already published. https://github.com/mockyeah/mockyeah/blob/gh-pages/CNAME

Supports #81.

### CODE REVIEW

**Comment by AndersDJohnson** [comment]
@ryanricard It works! http://mockyeah.js.org/ 🎉

**Comment by AndersDJohnson** [comment]
I've added a comment informing them here: https://github.com/js-org/dns.js.org/pull/1794#issuecomment-368267524

**Comment by ryanricard** [comment]
@AndersDJohnson I am not have any luck finding this PR build on Travis CI, any idea what happened?

**Comment by ryanricard** [comment]
Closing and reopening has kicked off CI.

**Comment by AndersDJohnson** [comment]
@ryanricard  CI died for a while due to the org rename. I reenabled it manually on Travis CI under my authority as an org admin.

**Pull request merged**
